# Generated by Django 5.1 on 2024-08-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_actor_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='directed_by',
        ),
        migrations.AddField(
            model_name='movie',
            name='directed_by',
            field=models.ManyToManyField(blank=True, related_name='direction_credits', to='movies.person'),
        ),
    ]
