# Generated by Django 5.1 on 2024-08-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_directed_by_movie_directed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativemovietitle',
            name='translation_difference_ratio',
            field=models.FloatField(default=1.0),
        ),
    ]
